// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SocialSite.Data;

namespace SocialSite.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20211022083851_AddUsers")]
    partial class AddUsers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SocialSite.Data.Models.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Client");

                    b.Property<DateTimeOffset>("CreatedAt");

                    b.Property<int>("Favorites");

                    b.Property<string>("Hashtags");

                    b.Property<string>("Language");

                    b.Property<string>("MediaType");

                    b.Property<string>("MediaUrls");

                    b.Property<string>("Mentions");

                    b.Property<string>("Name");

                    b.Property<string>("OriginalId");

                    b.Property<string>("ScreenName");

                    b.Property<int>("Shares");

                    b.Property<string>("Text");

                    b.Property<string>("Type");

                    b.Property<string>("Urls");

                    b.Property<int?>("UserId");

                    b.Property<DateTimeOffset>("Utc");

                    b.HasKey("MessageId");

                    b.HasIndex("UserId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("SocialSite.Data.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ProfilePictureLink");

                    b.Property<string>("ScreenName");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SocialSite.Data.Models.Message", b =>
                {
                    b.HasOne("SocialSite.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
